name: GitActions Demo1
on: push
jobs: 
  GitActions-demo-job: 
    name: Demo Job
    runs-on: ubuntu-latest
    steps: 
      - name: Print a enviromnet
        env: 
          MY_VAR: Hi there. My name is
          FIRST_NAME: dj
          LAST_NAME: kim
          AWS_JOB_NAME: kdj
        run: |
          echo $MY_VAR $FIRST_NAME $LAST_NAME.
          echo $MY_VAR $AWS_JOB_NAME.
